name: MineTunes
version: 1.5.0
main: com.mcmlr.minetunes.Minetunes
api-version: '1.20'
authors: [ The_Dude___ ]
folia-supported: true
description: Music streaming with a holographic GUI
commands:
  mt:
    description: Opens Mine Tunes
    usage: /.
  c:
    description: Closes Apps
    usage: /c
  k:
    description: Kills all Apps related entities
    usage: /k